### ISSUE TITLE
README: Why is your project better than simple_salesforce?

### ISSUE THREAD

**Issue by guettli** [felixlindstrom/python-salesforce-api#18]
I think many uses have this on their mind:

> Why is python-salesforce-api better than simple_salesforce?

It would be very kind if you could answer this question in the README.

Thank you.

**Comment by mattschofield** [comment]
The quick answer is that simple_salesforce is only suitable if you want to use the SOAP APIs - it doesn't work for the REST APIs. This repo does.

**Comment by felixlindstrom** [comment]
Hello!

Sorry for super late reply!

I'm not sure I want to compare this project with simple_salesforce in the readme. I had some problems expending simple_salesforce, as well as mocking salesforce requests for tests, which is why I created this project!

The aim was to create a project that was a bit more object oriented and extendable :)

**Comment by MattF-Afterpay** [comment]
Just wanted to add - Simple Salesforce doesn't support Bulk API v2.0, this package does. Which has been a life saver for me!

**Comment by felixlindstrom** [comment]
Nice to hear @MattF-Afterpay! The bulk-api was one of the main reasons I went and created this, along with being able to extend the metadata-api to allow me to write automated deployment-processes!
